### ISSUE TITLE
Plugin Not working correctly

### ISSUE THREAD

**Issue by Tavallaee** [kusimo/quick-download-button#3]
Hi
At first, Thank you Very much for your useul plugin
We install plugin in this website : [https://en.asiajarah.com](https://en.asiajarah.com)
We have problem when our users click on the botton and don't download files and appear "not found page".
Please check it 
Best regard

**Comment by Tavallaee** [comment]
For Example :
[https://en.asiajarah.com/product/laparoscopic-quick-lock-camera-cover/](https://en.asiajarah.com/product/laparoscopic-quick-lock-camera-cover/)

**Comment by Tavallaee** [comment]
https://en.asiajarah.com/laparoscopic-quick-lock-camera-cover/?aid=779&_wpnonce=72b443cb0b

I understand that this error occured for wpnonce but I can't solve it

**Comment by sidocodeyt** [comment]
Sorry for late reply, the issue has been solved in the latest version of the plugin, please download this on the WordPress repo https://wordpress.org/plugins/quick-download-button/. I will upload this to Github soon.
